# Generated by Django 5.0.1 on 2024-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.IntegerField(verbose_name=2),
        ),
        migrations.AlterField(
            model_name='details',
            name='height',
            field=models.IntegerField(verbose_name=3),
        ),
        migrations.AlterField(
            model_name='details',
            name='weight',
            field=models.IntegerField(verbose_name=3),
        ),
    ]
