# Generated by Django 5.0.1 on 2024-01-21 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_details_age_alter_details_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='photo',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
