# Generated by Django 5.0.1 on 2024-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_details_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='details',
            name='height',
        ),
        migrations.RemoveField(
            model_name='details',
            name='weight',
        ),
        migrations.AddField(
            model_name='details',
            name='cname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
