# Generated by Django 5.0.1 on 2024-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_details_age_remove_details_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
